### ISSUE TITLE
Horizontal scrolling for about us page

### ISSUE THREAD

**Issue by PekYC** [Racheltmz/IBED#11]
https://user-images.githubusercontent.com/91200212/135739643-94095d94-63a9-48eb-bcc0-915bd60e71fd.mp4

Hi @Racheltmz, 

I noticed this issue for the about us page, where the screen can be scrolled horizontally. Only once all the timeline elements have been shown, will the horizontal scrolling stop. I suspect the timeline elements are causing this problem.

**Comment by Racheltmz** [comment]
Yep it's the timeline elements that are causing this issue. They are initially positioned on the far right out of the screen so that they can ease in. I can try preventing the page from scrolling horizontally else I'll try another method for the timeline.

**Comment by Racheltmz** [comment]
Would it be fine if instead of the sections moving from right to left, I just let them appear while scrolling down. I can show yall this in a call if it's hard to visualise what I meant.

**Comment by PekYC** [comment]
> Would it be fine if instead of the sections moving from right to left, I just let them appear while scrolling down. I can show yall this in a call if it's hard to visualise what I meant.

Sure, maybe if we have the time, we could do it after our SPAI call at 11am
